name: tekartik_app_flutter_sembast
description: Sembast for flutter (Web, Mobile & Desktop)
version: 0.5.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sembast: ">=3.7.4+3"
  sembast_web: '>=2.4.0+3'
  sembast_sqflite: '>=2.0.0'
  path_provider:
  path: ">=1.9.0"
  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_sqflite
    version: '>=0.5.0'
  sqflite_common_ffi: ">=2.3.4"
  sqflite_common:
dev_dependencies:
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
  flutter_test:
    sdk: flutter
  process_run: ">=1.2.1+1"
  sqflite: ">=2.4.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
resolution: workspace

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
