name: tekartik_app_navigator_flutter
description: Experimental app navigator flutter
version: 0.4.9
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tekartik_app_flutter_bloc:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_bloc
    version: '>=0.2.2'
  collection: ">=1.18.0"
  path: ">=1.9.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.24.0"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
resolution: workspace

