name: tekartik_app_flutter_utils_repo
description: Repo
version: 0.1.0
homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dev_dependencies:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  process_run: '>=0.10.0'
# include all from git so that it makes a dependency check
  tekartik_app_emit:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: dart2
      path: app_emit

dependency_overrides:
# tmp
#  process_run:
#    path: ../process_run.dart