name: tekartik_app_roboto
description: Roboto fonts
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
resolution: workspace
