name: tekartik_app_lints_flutter
description: Tekartik flutter lints
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'

dev_dependencies:
  test: ">=1.24.0"
  path: ">=1.9.0"
  yaml: ">=3.1.2"
resolution: workspace
