name: tekartik_app_lints_flutter
description: Tekartik flutter lints
version: 0.1.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_lints:

dev_dependencies:
  test: ^1.16.0
  pedantic:
  tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'
