name: tekartik_app_dev_menu_flutter
description: "Quick dev menu flutter"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      path: test_menu_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=6.0.0"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter

resolution: workspace

# The following section is specific to Flutter packages.
flutter:

