name: tekartik_app_flutter_firebase_storage
description: Storage for flutter application
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  tekartik_firebase_storage_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: storage_flutter
    version: '>=0.4.0'
  tekartik_app_flutter_firebase:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_firebase
dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: ">=1.2.1+1"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
resolution: workspace

