name: app_flutter_utils_repo_support
description: App flutter utils repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
    version: '>=0.7.8'

  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
dependencies:
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      path: ci
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      path: packages/prj_tktools
resolution: workspace
