name: app_flutter_utils_repo_support
description: App flutter utils repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  path:
  pub_semver:
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: null_safety
    version: '>=0.1.0'
  process_run: '>=0.10.3'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: null_safety
    version: '>=0.7.8'

  test:
  dev_test:
  pedantic:
  tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'

