name: tekartik_app_roboto_test_app_lib
description: Widget test app lib
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  tekartik_app_flutter_common_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_common
    version: '>=0.1.0'
  tekartik_app_image_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_image
    version: '>=0.1.0'
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      path: test_menu_flutter
    version: '>=0.2.3'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.2.3'
  tekartik_app_flutter_widget:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_widget
    version: '>=0.1.0'
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_platform
    version: '>=0.1.0'
  tekartik_app_roboto:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_roboto
dev_dependencies:
  flutter_test:
    sdk: flutter
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'


flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: packages/tekartik_app_roboto/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: packages/tekartik_app_roboto/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        # missing
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Thin.ttf
        #  weight: 100
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          weight: 400
        # missing
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Medium.ttf
        #  weight: 500
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Black.ttf
        #  weight: 900
resolution: workspace
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
