name: tekartik_app_flutter_firebase_auth
description: Firebase auth for flutter application
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tekartik_app_flutter_firebase:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_firebase
      ref: dart2_3
  tekartik_firebase_auth_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: auth_flutter
      ref: dart2_3
    version: '>=0.7.0'
dev_dependencies:
  pedantic:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.3'
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart2_3
      path: packages/lints_flutter
    version: '>=0.1.0'
dependency_overrides:
  tekartik_app_flutter_firebase:
    path: ../app_firebase